name: terraform-destroy
on:
  workflow_dispatch:
jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: Init / Destroy (remote on TFC)
        working-directory: .
        run: |
          terraform init -input=false
          terraform destroy -auto-approve -input=false
